### ISSUE TITLE
Creation of the SRS

### ISSUE THREAD

**Issue by Mitrixlance** [Mitrixlance/Analisis_Puzzle#1]
Important, Definition of requirements until friday midnight

**Comment by Mitrixlance** [comment]
Definition of requirements have been completed, formal SRS still needed

**Comment by yorchpave** [comment]
El alcanze del proyecto ya fue definido, falta agregar introducción.

**Comment by Mitrixlance** [comment]
Introduction added and some modifications to the scope added

**Comment by yorchpave** [comment]
Final SRS version has been uploaded.
