### ISSUE TITLE
Story boards

### ISSUE THREAD

**Issue by Mitrixlance** [Mitrixlance/Analisis_Puzzle#2]

**Comment by Mitrixlance** [comment]
There is an upload to the drive where you can see the story, check out necesary so we can use it on the presentation and the integration of the main document.

**Comment by yorchpave** [comment]
Ya esta revisada la story, sera incluida dentro de la presentación.

**Comment by Mitrixlance** [comment]
Checking the story with some people it is added the use of scores, and it has been added to the requirements.
